version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_pass
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: /app/entrypoint.sh
    volumes:
      - ./backend:/app
      - media_data:/app/media
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_pass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
  media_data:
