version: '3.8'

services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    command: sh -c "npm install && npm run build"

  db:
    image: postgres:14
    container_name: foodgram-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_pass
    ports:
      - "5432:5432"

  backend:
    container_name: foodgram-back
    build: ../backend
    command: /app/entrypoint.sh
    volumes:
      - ../backend:/app
      - media_data:/app/media
      - ../data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_pass
      DB_HOST: db
      DB_PORT: 5432

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  media_data:
  frontend_build:
